name: GitHub Actions Practice

on: ["push"]

jobs:
  log:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: say-hi
        run: echo "Hi developer!"
      
      
      
      
